collegechamps/blog/routes.py
from io import TextIOWrapper
import os
from slugify import slugify
from re import sub
import secrets
from flask import render_template, url_for, flash, redirect, request, Blueprint, session, request
from flask_login import login_user, current_user, logout_user, login_required
from flask_wtf.recaptcha.widgets import RecaptchaWidget
from collegechamps import db, app
from collegechamps.blog.forms import PostForm
from collegechamps.models import Set, Post
from collegechamps.users.forms import RegistrationForm
from werkzeug.utils import secure_filename
from PIL import Image
import json
from datetime import datetime, timezone

db_username = os.environ.get('DB_USERNAME')
db_pw = os.environ.get('DB_PASSWORD')

with open('mcq.json', 'r') as c:
    params = json.load(c)["params"]

blogs = Blueprint('blogs', __name__)

@blogs.route('/blog_page')
def blog_page():
    side_posts = Post.query.filter_by(others2 = 'sidebar')

    posts = Post.query.filter_by(
        slug='blog', others1='article').order_by(Post.date_posted.desc())
    # notes = Post.query.filter_by(slug = 'note')
    notes = Post.query.filter_by(slug='blog', others1='note')

    return render_template('blog_page.html', background="sc-6", heading='CollegeChamps', sub_header='Blog Page', posts=posts, notes=notes, side_posts = side_posts)


@blogs.route('/post/<int:post_id>/')
def post(post_id):
    feats = Post.query.filter_by(featured='featured')
    post = Post.query.get_or_404(post_id)
    # to_slugify = Post.query.filter_by(title = title).first()
    # slug_title = to_slugify.replace(" ","-")
    return render_template('post.html', title=post.title, post=post, feats=feats)


# @blogs.route('/<url_slug>', methods = ['GET'])
# def spost(url_slug):
#     feats = Post.query.filter_by(featured='featured')
#     post = Post.query.get_or_404(url_slug)
#     # to_slugify = Post.query.filter_by(title = title).first()
#     # slug_title = to_slugify.replace(" ","-")
#     return render_template('post.html', title=post.title, post=post, feats=feats)
# @blogs.route('/<post_id>/<slug>')

# def postp(post_id, slug):

#     """ find the post and then show it """
#     p = Post.query.get(post_id)
#     return render_template("post.html", post=p)


@blogs.route('/post_page')
def post_page():
    return render_template('postpage.html')


@blogs.route('/ioe_entrance/ioe-notes')
def notes():
    notes = Post.query.filter_by(others1='note')
    return render_template('post.html', notes=notes)


@blogs.route('/ioe_entrance/ioe-notes/<int:note_id>')
def note_ids(note_id):
    feats = Post.query.filter_by(featured='featured')
    notes = Post.query.get_or_404(note_id)
    return render_template('notes.html', note=notes, feats=feats)


@blogs.route('/featured')
def featured_posts():
    feats = Post.query.filter_by(featured='featured')
    return render_template('featured.html', feats=feats)

# @blogs.route('/featured')
# def post():
#     feats = Post.query.filter_by(featured = 'featured')
#     return render_template('post.html',feats = feats)


@blogs.route('/featured/<int:feat_id>')
def featured_ids(feat_id):
    feat = Post.query.get_or_404(feat_id)
    feats = Post.query.filter_by(featured='featured')
    return render_template('featured.html', feat=feat, feats=feats)




@blogs.route("/dashboard", methods=["GET", "POST"])
def dashboard():
    form = RegistrationForm()
    if ('user' in session and session['user'] == db_username):
        posts = Post.query.all()
        see_posts = Post.query.filter_by(slug  = 'set_page', subject_title = 'see')
        articles = Post.query.filter_by(slug  = 'blog', others1 = 'article')
        notes = Post.query.filter_by(slug  = 'blog', others1 = 'note')
        return render_template('dashboard.html', posts=posts,see_posts = see_posts,articles = articles,notes=notes)

      

    if request.method == "POST":
        username = form.username.data
        userpass = form.password.data
        if username == db_username and userpass == db_pw:
            session['user'] = username
            posts = Post.query.all()
            see_posts = Post.query.filter_by(slug  = 'index')
            flash('Welcome to the dashboard', 'succes')
            return render_template('dashboard.html', posts=posts,see_posts = see_posts)
        else:
            flash('Retype The password or the username ', 'error')
    return render_template('dashboard_sign_in.html', form=form)


def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(
        app.root_path, 'static/profile_pics', picture_fn)

    basewidth = 250
    # output_size = (200, 200)
    i = Image.open(form_picture)
    wpercent = (basewidth/float(i.size[0]))
    hsize = int((float(i.size[1])*float(wpercent)))
    i = i.resize((basewidth,hsize), Image.ANTIALIAS)
    # i.thumbnail(output_size)
    i.save(picture_path)
   

    return picture_fn

# blog Posts


@blogs.route("/postNew/<string:parameter>", methods=['GET', 'POST'])
def postNew(parameter):

    if ('user' in session and session['user'] == db_username):
        posts = Post.query.all()
        form = PostForm()
        if parameter == 'index':
            form.slug.data = 'index'
            # flash_kw = 'index'
            form.content.data = "_"
        if parameter == 'set_page':
            form.slug.data = 'set_page'
            # flash_kw = 'Sets'

        if form.validate_on_submit():
            title = form.title.data
            slug = form.slug.data
            content = form.content.data
            subtitle = form.subtitle.data
            price = form.price.data
            subject_title = form.subject_title.data
            pic = request.files['pic']
            if pic:
                pic = save_picture(request.files['pic'])
            else:
                pic = 'hello.png'
            to_redirect = form.to_redirect.data
            post = Post(title=title, slug=slug, subtitle=subtitle, img=pic,
                        to_redirect=to_redirect, content=content, price=price, subject_title=subject_title)
            db.session.add(post)
            db.session.commit()
            # {flash_kw}
            flash(f'Your post has been created for  page!', 'succes')
            # if parameter =='continue_editing':
            #     return redirect('blogs.update_post',post_id =post.id)
               
            return redirect('blogs.dashboard')
        return render_template('create_post.html', title='You are posting on the index page',
                               form=form, posts =posts ,parameter=parameter)

    return "please login to the dashboard first. Dont try to enter without logging in!"


@blogs.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    posts = Post.query.all()
    if ('user' in session and session['user'] == db_username):
        form = PostForm()
        if form.validate_on_submit():
            post.title = form.title.data
            post.content = form.content.data
            post.slug = form.slug.data
            post.subtitle = form.subtitle.data
            post.to_redirect = form.to_redirect.data
            post.price = form.price.data
            pic = request.files['pic']
            if pic:

                post.img = save_picture(request.files['pic'])
            else:
                pass

            db.session.commit()
            flash('Your post has been updated!', 'succes')
            return redirect(url_for('blogs.dashboard'))
        elif request.method == 'GET':
            form.title.data = post.title
            form.content.data = post.content
            form.slug.data = post.slug
            form.subtitle.data = post.subtitle
            form.to_redirect.data = post.to_redirect
            form.price.data = post.price

        return render_template('create_post.html', title='Update Post',posts=posts,
                               form=form, legend='Update Post')
    return "please login to the dashboard first. Dont try to enter without logging in!"


@blogs.route("/post/<int:post_id>/delete", methods=['GET', 'POST'])
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if ('user' in session and session['user'] == db_username):
     
        db.session.delete(post)
        db.session.commit()
        flash('Your post has been deleted!', 'info')
        return redirect(url_for('blogs.dashboard'))

    return "please login to the dashboard first. Dont try to enter without logging in!"

# set posts
# @blogs.route('/set_post/new', methods=['GET', 'POST'])
# def set_post():
#     if ('user' in session and session['user'] == params["username"]):
#         form = PostForm()
#         if form.validate_on_submit():
#             set_card = Set(title=form.title.data, content=form.content.data, price=form.price.data,
#                            mock_title=form.mock_title.data, mock_content=form.mock_content.data)
#             db.session.add(set_card)
#             db.session.commit()
#             flash('Your set has been created!', 'success')
#             return redirect(url_for('blogs.dashboard'))
#         return render_template('create_post.html', title='New Set',
#                                form=form)

#     return "please login to the dashboard first. Dont try to enter without logging in!"


@blogs.route('/set_page')
def set_page():
    sets = Post.query.filter_by(slug='set_page',subject_title = 'see')
    return render_template('sets_page.html', sets=sets, header = '+2 Entrance Preparation',title = '+2 Entrance Preparation')


@blogs.route('/individual_set/<int:set_id>/')
def individual_set(set_id):
    individual_page = Post.query.get_or_404(set_id)
    # limit = Post.query.all(others=25).first()
    return render_template('forms_page.html', individual_page=individual_page,times_limit = 25)

collegechamps/main/routes.py
# main/routes.py
from flask import render_template, request, Blueprint, redirect
from flask_login import login_required
from collegechamps.models import User,Post


main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():

    side_posts = Post.query.filter_by(others2 = 'sidebar')
    posts = Post.query.filter_by(slug = 'index')
    return render_template('index.html',posts = posts ,side_posts = side_posts)

# @main.route('/sidebar_elem/<int:side_id>')
# def sidebar_elem(side_id):
#     side_id = side.

@main.route("/ioe")
def ioe():
    return render_template('ioe.html')


@main.route("/blog_notes")
def blog_notes():
    return render_template('blog_notes.html')

@main.route('/CollegeChamps/privacy-policy/<parameter>')
def privacy_policy(parameter):
    side_posts = Post.query.filter_by(others2 = 'sidebar')
    return render_template('privacy_policy.html',side_posts= side_posts, parameters =parameter)


# @main.route("/mcqsection")
# @login_required
# def mcqsection():
#     return render_template('mcqsection.html')



# @main.route("/about")
# def about():
#     return render_template('about.html', title='About')

collegechamps/templates/blog_notes.html
{% extends 'render.html' %}
{% block showcase_nav_foot %}
  

  
<div class="showcase">
  <div class="main-container">
    <h1 id="animate" class="showcase-maintext">Not Decided</h1>
    <p class="showcase-subtext">Name Not Decided Yet..</p>
    <a href="{{url_for('main.home')}}" class="btn-secondary"
      >Practice Now <i class="fas fa-chevron-down"></i
    ></a>
  </div>
</div>
{%endblock%}
{% block sectionA %}
  <div>
    <div class="main-container">
      <div class="card-grid-container">
        <div class="card card1 less-margin ">
          <div class="img_link_grid">
           <img class= 'card_image' src="{{ url_for('static', filename='img/maths-min.png') }}"alt="">
            <div>
              <h1 class="chapter-name">Algebra</h1>
           
              <a href="hall.html" class="btn-primary">Start </a>
            </div>
          </div>
        </div>
        <div class="card card1 less-margin ">
          <div class="img_link_grid">
           <img class= 'card_image' src="{{ url_for('static', filename='img/maths-min.png') }}"alt="">
            <div>
              <h1 class="chapter-name">Physics</h1>
           
              <a href="hall.html" class="btn-primary">Start </a>
            </div>
          </div>
        </div>
        <div class="card card1 less-margin ">
          <div class="img_link_grid">
           <img class= 'card_image' src="{{ url_for('static', filename='img/maths-min.png') }}" alt="">
            <div>
              <h1 class="chapter-name">Biology</h1>
           
              <a href="hall.html" class="btn-primary">Start </a>
            </div>
          </div>
        </div>
        <div class="card card1 less-margin ">
          <div class="img_link_grid">
           <img class= 'card_image' src="{{ url_for('static', filename='img/maths-min.png') }}"alt="">
            <div>
              <h1 class="chapter-name">Chemistry</h1>
           
              <a href="hall.html" class="btn-primary">Start </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock sectionA %}
  </body>
</html>

collegechamps/templates/blog_page.html
{% extends "render.html" %}
{% block showcase_nav_foot %}
<!-- end of navbar -->
<div class="showcase {{background}} ">
  <div class="main-container">
    <h1 id = 'animate'class="showcase-maintext">{{heading}}</h1>
    <p class="showcase-subtext">{{sub_header}}</p>
    <a href="subject1.html" class="{{button}} btn-secondary">Practice Now</a>
  </div>
</div>
{% endblock showcase_nav_foot %}
<!-- new section test -->
{% block sectionA %}
  

<div class="container-post">
<div class="blog-heading">
  <p>Notes</p>
</div>
<div >
  <div class="blog-new-card-grid-post">
    <div class="slideshow-container">
      {% for note in notes %}
      <div class="mySlides fade">
        <a href="{{ url_for('blogs.note_ids',note_id = note.id) }}">
        <h1 class="carousel_heading card-b2">{{note.title}}</h1>
      </a>
      </div>
      {%endfor%}
      <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
      <a class="next" onclick="plusSlides(1)">&#10095;</a>
    </div>
  </div>
  <div class="blog-heading">
    <p>Articles</p>
  </div>
  <div class="post-container">
    {% for post in posts %} {% set img_name = 'profile_pics/' + post.img %} {%
    set img_name = 'profile_pics/' + post.img %} {% set day =
    post.date_posted.strftime('%B') %} {% set day_num = post.date_posted.day%}
    {% set year = post.date_posted.year%}
    {% set slug_t = post.title.replace(" ","-").lower() %}
    <div class="blog-new-card">
      <div class="blog-card card-b2">
        <div class="meta">
          <div class="photo" style="background-image: url()">
            <img src="{{url_for('static', filename = img_name)}}" alt="error" / width = 225px height = 200px >
          </div>
          <ul class="details">
            <!-- <li class="author"><a href="#">Admin</a></li> -->
            <!-- <li class="date">{{post.date_posted}}</li> -->
          </ul>
        </div>

        <div class="description">
          <a href="{{url_for('blogs.post',post_id=post.id,slug = slug_t)}}"
            ><h6 class="title">{{post.title}}</h6></a
          >
          <small>{{day_num}} {{day}} {{year}}</small>
          <!-- <h2>Opening a door to the future</h2> -->
          <div class="fit-text"><p class>{{post.subtitle}}</p></div>

          <p class="read-more">
            <a href="{{url_for('blogs.post',post_id=post.id,slug = slug_t)}}">Read More</a>
          </p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
</div>
<!-- {% if 'user' in session %}

<a class="add_post_logo" href="{{url_for('blogs.postNew',parameter = 'blog')}}"
  >&#x2b;</a
>
  
{% endif %} -->

<!-- End of shwocase  -->
<!-- <div class="sc-3 showcase">
      <div class="main-container">
        <h1 class="showcase-maintext  mb-1">IOE / IOM</h1>
    
        <a href="ioe.html" class="sc3-btn btn-secondary">Continue <i class="fas fa-chevron-right"></i> </a>
      </div>
    </div> -->

<!-- End of chemistry section -->
<!-- <div class="sc-4 showcase">
  <div class="main-container">
    <div class="g1">
      <h1 class="showcase-maintext  mb-1">+2 Entrance</h1>
      <a href="subject1.html" class="btn-secondary sc4-btn">Continue <i class="fas fa-chevron-right"></i></a>
    </div>
    <div class="g2">
  </div>
  
  </div> -->

<script>
  var slideIndex = 1;
  showSlides(slideIndex);

  function plusSlides(n) {
    showSlides((slideIndex += n));
  }

  function currentSlide(n) {
    showSlides((slideIndex = n));
  }

  function showSlides(n) {
    var i;
    var slides = document.getElementsByClassName("mySlides");
    var dots = document.getElementsByClassName("dot");
    if (n > slides.length) {
      slideIndex = 1;
    }
    if (n < 1) {
      slideIndex = slides.length;
    }
    for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";
    }
    for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
    }
    slides[slideIndex - 1].style.display = "block";
    dots[slideIndex - 1].className += " active";
  }
</script>
{% endblock sectionA %}

collegechamps/templates/dashboard.html
{% extends 'layout.html' %} {% block navbar %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/dashboard.css') }}"
/>
<style>
  .admin-container {
    /* margin: auto; */
  }
  .admin_panel_head {
    background: rgb(234, 234, 234);
    padding: 10px;
  }
  .posts-table {
    font-family: "Open Sans", sans-serif;
    border-collapse: collapse;
    width: 100%;
    font-size: 18px;
  }
  .posts-table td,
  .posts-table th {
    border: 1px solid black;
    text-align: center;
  }
  .admin-panel-content-grid {
    margin: 10px;
    display: grid;
    grid-template-columns: 3fr 2fr 2fr 2fr;
    grid-gap: 20px;
    width :auto;
    overflow: visible;
    align-items: flex-start;
    justify-content: center;
  }
</style>

<div class="admin-container">
  <div class="admin-panel">
    <h1 class="admin_panel_head">Admin Panel</h1>
  </div>
  <div class="for-misc">
    <a  class="btn-for-dashboard" href="{{url_for('blogs.postNew',parameter = 'index')}}">Add A New Post</a>
    
  </div>
  <div class="admin-panel-content-grid">
    <div class="posts-container">
      <table class="posts-table">
        <tr>
          <th>Index</th>
          <th>Posts</th>
          <th>slug</th>
          <th>Subject Title</th>
          <th>Methods</th>
        </tr>
        {% for post in posts %}
        <tr>
          <td>{{post.id}}</td>
          <td>{{post.title}}</td>
          <td>{{post.slug}}</td>
          <td>{{post.subject_title}}</td>
          <td>
            <a
              class="btn-for-dashboard"
              href="{{ url_for('blogs.update_post', post_id=post.id) }}"
              >Update</a
            >
            <a
              class="btn-for-dashboard"
              href="{{ url_for('blogs.delete_post', post_id=post.id) }}"
              >Delete</a
            >
          </td>
        </tr>
        {% endfor %}
      </table>
    </div>
    <div class="home-page-content">
      <div class="admin-panel-content-grid">
        <div class="posts-container">
          <a  class="btn-for-dashboard" href="{{url_for('blogs.postNew',parameter = 'set_page')}}">Add A New See Set</a>
          <table class="posts-table">
            <tr>
              <th>Index</th>
              <th>Posts</th>
              <th>slug</th>
              <th>Subject Title</th>
              <th>Methods</th>
            </tr>
    
            {% for see_set in see_posts %}
          
            <tr>
              <td>{{see_set.id}}</td>
              <td>{{see_set.title}}</td>
              <td>{{see_set.slug}}</td>
              <td>{{see_set.subject_title}}</td>
              <td>
                <a
                  class="btn-for-dashboard"
                  href="{{ url_for('blogs.update_post', post_id=see_set.id) }}"
                  >Update</a
                >
                <a
                  class="btn-for-dashboard"
                  href="{{ url_for('blogs.delete_post', post_id=see_set.id) }}"
                  >Delete</a
                >
              </td>
            </tr>
            {% endfor %}
          </table>
    </div>
    <div class="add-content-ioe">
      <h1>Manage Cards</h1>
      <a  class="btn-for-dashboard" href="{{url_for('blogs.postNew',parameter = 'articles')}}">Add A New Article</a>
          <table class="posts-table">
            <tr>
              <th>Index</th>
              <th>Posts</th>
              <th>slug</th>
              <th>Subject Title</th>
              <th>Methods</th>
            </tr>
    
            {% for article in articles %}
          
            <tr>
              <td>{{article.id}}</td>
              <td>{{article.title}}</td>
              <td>{{article.slug}}</td>
              <td>{{article.subject_title}}</td>
              <td>
                <a
                  class="btn-for-dashboard"
                  href="{{ url_for('blogs.update_post', post_id=article.id) }}"
                  >Update</a
                >
                <a
                  class="btn-for-dashboard"
                  href="{{ url_for('blogs.delete_post', post_id=article.id) }}"
                  >Delete</a
                >
              </td>
            </tr>
            {% endfor %}
          </table>
    </div>
    <div class="add-content-see">
      <h1>Link Go to SEE PAGE</h1>
      <h1>Manage Cards and sets</h1>
    </div>
  </div>
</div>


{% endblock navbar %}

collegechamps/templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Footer Design</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/footer.css') }}">
  <!-- <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"> -->
</head>
<body>

  <footer class="footer">
  	 <div class="container">
  	 	<div class="row">
  	 		<div class="footer-col">
  	 			<h4>CollegeChamps</h4>
  	 			<ul>
  	 				<li><a href="#">About Developer</a></li>
  	 				<li><a href="{{url_for('main.privacy_policy',parameter = 'privacy_policy')}}">Privacy Policy</a></li>
  	 				<li><a href="{{url_for('main.privacy_policy',parameter = 'credits')}}">Credits></li>
  	 				<li><a href="#">Contact Me</a></li>
					   <li><a href="#">Donate</a></li>
					   
  	 			</ul>
  	 		</div>
  	 		<div class="footer-col">
  	 			<h4>IOE/IOM</h4>
  	 			<ul>
  	 				<li><a href="#">Physics</a></li>
  	 				<li><a href="#">Mathematics</a></li>
  	 				<li><a href="#">English</a></li>
  	 				<li><a href="#">Biology</a></li>
  	 				<li><a href="#">English</a></li>
  	 				
  	 			</ul>
  	 		</div>
  	 		<div class="footer-col">
  	 			<h4>Others</h4>
  	 			<ul>
  	 				<li><a href="#">+2 Entrance</a></li>
  	 				<li><a href="#">Blog Page</a></li>
  	 			
  	 			</ul>
  	 		</div>
  	 		<div class="footer-col">
  	 			<h4>follow us</h4>
  	 			<div class="social-links">
  	 				<a href="#"><i class="fab fa-facebook-f"></i></a>
  	 				<a href="#"><i class="fab fa-twitter"></i></a>
  	 				<a href="#"><i class="fab fa-instagram"></i></a>
  	 				<a href="#"><i class="fab fa-linkedin-in"></i></a>
  	 			</div>
				   <p  class = 'copyright'>&#169; 2021 CollegeChamps Aadarsh Baral</p>

  	 		</div>
  	 	</div>
		 
  	 </div>
  </footer>
{% block footer %}
  
{% endblock footer %}
</body>
</html>

collegechamps/templates/index.html
{% extends 'render.html' %}
<!-- end of navbar -->
{% block showcase_nav_foot %}

<div class="showcase">
  <div class="main-container">
    <h1 id="animate" class="showcase-maintext">Not Decided</h1>
    <p class="showcase-subtext">Name Not Decided Yet..</p>
    <a href="#s1" class="btn-secondary">Practice Now</a>

    <a class="no-2-btn btn-secondary" href="{{ url_for('blogs.blog_page') }}">
      Blog Page</a
    >
  </div>
</div>
{% endblock showcase_nav_foot %} {% block sectionA %}
<div>
  {% for post in posts %} {% set img_name = 'profile_pics/' + post.img %} {% set
  img_name = 'profile_pics/' + post.img %} {% set day =
  post.date_posted.strftime('%B') %} {% set day_num = post.date_posted.day%} {%
  set year = post.date_posted.year%}
  {% if post.to_redirect %} {% set redirect = post.to_redirect %} {%
    else%} {% set redirect = 'main.home' %} {% endif %}
  <div class="blog-new-card">
    <div class="blog-card">
      <div class="meta">
        <div class="photo" style="background-image: url()">
          <img src="{{url_for('static', filename = img_name)}}" alt="error" /
         width = 225px height = 200px >
        </div>
        <ul class="details">
          <!-- <li class="author"><a href="#">Admin</a></li> -->
          <!-- <li class="date">{{post.date_posted}}</li> -->
        </ul>
      </div>

      <div class="description"> 
        <!-- <a href="{{url_for('blogs.post',post_id=post.id,slug = post.title)}}" -->
          {% set slug_t = post.title.replace(" ","-").lower() %}
          
        
         <a href="{{ url_for(redirect) }}""><h6 class="title">{{post.title}}</h6></a>
        <!-- <small>{{day_num}} {{day}} {{year}}</small> -->
        <!-- <h2>Opening a door to the future</h2> -->
        <div class="fit-text"><p class>{{post.subtitle}}</p></div>

        <p class="read-more">
          <a href="{{ url_for(redirect) }}"">Read More</a>
        </p>
        
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% include 'sidebar.html' %}
<!-- {% if 'user' in session %}
<a class="add_post_logo" href="{{url_for('blogs.postNew',parameter = 'index')}}"
  >&#x2b;</a
>
{% endif %} -->

<!-- <script>
  $("a").click(function () {
    $("html, body").animate(
      {
        scrollTop: $($(this).attr("href")).offset().top,
      },
      500
    );
    return false;
  });
</script> -->

{% endblock sectionA %}

collegechamps/templates/showcase.html
{% block showcase %}
<div class="showcase">
  <div class="main-container">
    <h1 id="animate" class="showcase-maintext">Not Decided</h1>
    <p class="showcase-subtext">Name Not Decided Yet..</p>
    <a href="{{url_for('main.home')}}" class="btn-secondary"
      >Practice Now <i class="fas fa-chevron-down"></i
    ></a>
  </div>
</div>  
{% endblock showcase %}

collegechamps/templates/sidebar.html
<!-- <div class="fe  atured-categories">
  {% for side_post in side_posts %}
  <div>
    <img src="" alt="error" width="120px" height="110px" />
    <div class="categories-para-grid">
      <p>{{side_post.title}}</p>
      <p>September 9, 2021</p>
    </div>
  </div>
  {% endfor %}
</div>

<div class="extra_category" style="display: none">
  <div>
    <img
      src="https://source.unsplash.com/random"
      alt="error"
      width="90px"
      height="80px"
    />
    <p>This is a test post</p>
  </div>
</div> -->

collegechamps/templates/subject.html
{% extends 'render.html' %} {% block showcase_nav_foot %}

<div class="{{background}} showcase">
  <div class="main-container">
    <h1 class="showcase-maintext">{{heading}}</h1>
    <p class="showcase-subtext">{{sub_header}}</p>
    <a href="{{ url_for('blogs.blog_page') }}" class="{{button}} btn-secondary"
      >View Notes</a
    >
  </div>
</div>
{% endblock showcase_nav_foot %} {% block sectionA %}
<div>
  <div class="main-container">
    <div class="card-grid-container">
      <!-- topic is a list with dictionary key value pairs 
    topic = [{key : value}] -->
      {% for topic in topics %} {% for key in topic %} {% set topic_header =
      topic[key].replace('_',' ') %}
      <div class="card {{cardBackground}} card1">
        <h1 class="chapter-name">{{topic_header| capitalize}}</h1>
        <div class="line"></div>
        {% set route = topic[key] %} {%set main_route = "subjects.%s" % route %}
        <a href="{{ url_for(main_route) }}" class="btn-primary">Start </a>
      </div>
      {% endfor %} {% endfor %}
    </div>
  </div>
</div>
  {% endblock sectionA %} {% if 'user' in session %}
  <a
    class="add_post_logo"
    href="{{url_for('blogs.postNew',parameter = 'index')}}"
    >&#x2b;</a
  >
  {% endif %}

collegechamps/templates/test_for.html
{% if 'user' in session %}
<a
  class="add_post_logo"
  href="{{url_for('blogs.postNew',parameter = 'index')}}"
  >&#x2b;</a
>
{% endif %}